### ISSUE TITLE
Internet down pervention.

### ISSUE THREAD

**Issue by joaocps** [joaocps/magic-mirror-async#4]
```
2021-03-08 21:27:57 kali library.apis[3149] ERROR Server disconnected
2021-03-08 21:27:57 kali asyncio[3149] ERROR Task exception was never retrieved
future: <Task finished name='Task-1' coro=<News.get_headlines() done, defined at /home/kali/Desktop/magic-mirror-async/smartmirror.py:180> exception=AttributeError("'NoneType' object has no attribute 'encode'")>                        
Traceback (most recent call last):
  File "/home/kali/Desktop/magic-mirror-async/smartmirror.py", line 196, in get_headlines
    news_pt = await location_pt.get(api)
  File "/home/kali/Desktop/magic-mirror-async/library/apis.py", line 71, in get
    news = News(raw_news)
  File "/home/kali/Desktop/magic-mirror-async/library/news.py", line 11, in __init__
    self._data = feedparser.parse(data)
  File "/home/kali/Desktop/magic-mirror-async/virtualenv/lib/python3.9/site-packages/feedparser/api.py", line 214, in parse
    data = _open_resource(url_file_stream_or_string, etag, modified, agent, referrer, handlers, request_headers, result)
  File "/home/kali/Desktop/magic-mirror-async/virtualenv/lib/python3.9/site-packages/feedparser/api.py", line 134, in _open_resource
    return url_file_stream_or_string.encode('utf-8')
AttributeError: 'NoneType' object has no attribute 'encode'
-----------------------------------------------------------------------------
```--------------------------
2021-03-08 21:19:13 kali library.apis[3149] ERROR Server disconnected
2021-03-08 21:19:13 kali asyncio[3149] ERROR Task exception was never retrieved
future: <Task finished name='Task-3' coro=<Weather.get_weather() done, defined at /home/kali/Desktop/magic-mirror-async/smartmirror.py:281> exception=TypeError("'NoneType' object is not subscriptable")>                                 
Traceback (most recent call last):
  File "/home/kali/Desktop/magic-mirror-async/smartmirror.py", line 297, in get_weather
    if weather.current_temperature != self.temperature:
  File "/home/kali/Desktop/magic-mirror-async/library/weather.py", line 20, in current_temperature
    return round(self._data['current']['temp'])
TypeError: 'NoneType' object is not subscriptable

**Comment by joaocps** [comment]
Fixed with try except asyncio.TimeoutError but needs some improvements
